# Only used for external testing of app-b
# leaving here per note in readme

#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: app-b-halo-sh
#  namespace: default
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: "/" # exposing as a directory below so we need to rewrite url
#spec:
#  rules:
#  - host: app-a.halo.sh
#    http:
#      paths:
#      - path: "/auth-svc"  # exposing this just for sake of proving this project, wouldn't expose if not needed
#        backend:
#          serviceName: app-b
#          servicePort: 80
#  tls:
#  - secretName: halo-sh-tls