apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-b
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-b
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
